apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-thing-backend
  name: k8s-thing-backend-service
spec:
  selector:
    app: k8s-thing-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
